### PR TITLE
Basic contributing guide

### PR DESCRIPTION
**Pull request by tigleym**
This work adds a basic contributing guide for anyone looking to make contributions.

### CODE REVIEW

**Comment by tigleym** [comment]
For #59

**Review by cdsupina — APPROVED** [review]

**Comment by cdsupina** [comment]
I think this is well put! I think the only thing we should add in the future is links to custom issue tags specifically for good starting issues like a stat enhancing items.

**Comment by cdsupina** [comment]
I also think we should mention artwork somewhere, but maybe that belongs in a future mdbook.

**Comment by tigleym** [comment]
Agreed that we should eventually have links to feature-specific good issues. Adding new items is a good place to start! I'm hoping to get a guide for adding items in soon to help people work on "item adding" issues in the future.

In the meantime, I think it's worth mentioning in CONTRIBUTING.md what tools are used (and alternatives), expected canvas sizes for items, enemies, etc... I think once we get an mdbook we can migrate these guides there and provide  links to them in CONTRIBUTING.md

**Pull request merged**
