### PR TITLE
[Close #10] Add item that increases max health

### LINKED ISSUE #10: Add item to item pool that increases the total health of the spaceship
Add item to item pool that increases the total health of the player by a reasonable amount.

### PR DESCRIPTION
**Pull request by aquarhead**
BTW I noticed the `items.ron` file is using CRLF for line ending but `item.rs` is using just LF. Not sure if that is intentional?

### CODE REVIEW

**Comment by cdsupina** [comment]
I noticed that you left the sprite index that same as the "double barrel" item. Do you want to try making your own sprite and setting the index to that?

**Comment by aquarhead** [comment]
Oh yeah, sorry I forgot to ask about it.

I have no experience in digital drawing xD, is there any source on the web that you can just grab? Or did you draw all the other sprites?

**Comment by aquarhead** [comment]
And also do you just edit the spritesheet directly (with image editors?) or use some tool to package it?

**Comment by cdsupina** [comment]
I drew the sprites myself. I recommend using Gimp. Just edit it and overwrite the existing png file. Don't hesitate to post questions about Gimp if you have any trouble. Only requirement is to have the gold outline like the others do.

https://www.gimp.org/

**Comment by cdsupina** [comment]
So someone else did a pull request for the same issue minutes before you added your changes. I merged theirs because it was up to date with master.

However, I see no issue with having more than one health modifying items (just like binding of isaac). If you resolve the conflicts and catch up the branch with master I would be happy to merge yours as well. I really like the sprite you created.

**Comment by cdsupina** [comment]
Looks good.

**Pull request merged**
